resProj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path, include

# import actual view you want to use to avoid confusion
from pages.views import HomeListView, contact_view, about_view
from reservations.views import ReservationListView



urlpatterns = [
    path('restraunts/', include('restraunts.urls')),
    path('reservations/', include('reservations.urls')),
    path('admin/', admin.site.urls),
    path('',  HomeListView.as_view(), name='home'),
    path('contact/', contact_view),
    path('about/', about_view),
    

    path('accounts/', include('allauth.urls')),
    
   
  
]

restraunts/urls.py
from django.urls import path
from .views import(
    RestrauntView,
    RestrauntListView,
    RestrauntCreateView,
    RestrauntUpdateView,
    RestrauntDeleteView,
    RestrauntReservationCreateView,
    searchRest,
    RestrauntReservationsView,

)
  

app_name = 'restraunts'
urlpatterns = [

    path('', RestrauntListView.as_view(), name = 'restraunts-list'),
    path('create/', RestrauntCreateView.as_view(), name = 'restraunts-create'),
    path('<int:id>', RestrauntView.as_view(), name = 'restraunts-detail'),
    path('<int:id>/update/', RestrauntUpdateView.as_view(), name = 'restraunts-update'),
    path('<int:id>/reserve/', RestrauntReservationCreateView.as_view(), name = 'restraunts-reserve'),
     path('<int:id>/reservations/', RestrauntReservationsView.as_view(), name = 'restraunts-reservations'),
    path('<int:id>/delete/', RestrauntDeleteView.as_view(), name = 'restraunts-delete'),
    path('search/', searchRest, name = 'searchRest'),
    
]

restraunts/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Restraunt(models.Model):
    name            = models.CharField(max_length = 36)
    city            = models.CharField(max_length = 16)
    address         = models.CharField(max_length = 36)
    state           = models.CharField(max_length = 16)
    seatsAvailable  = models.IntegerField()
    cuisine         = models.CharField(max_length = 16)
    beginTime       = models.TimeField()
    endTime         = models.TimeField()
    priceRange      = models.CharField(max_length = 16)
    
   
DEFAULT_ID = 1

class ReservationDate(models.Model): 
    restraunt       = models.ForeignKey(Restraunt, on_delete = models.CASCADE, default = DEFAULT_ID)
    date            = models.DateField(default = timezone.now)

class TodayReservation(models.Model):
    # Don't need this but not enough time to change
    reservationDate     = models.ForeignKey(ReservationDate, on_delete = models.CASCADE, default = DEFAULT_ID)
 

class ReservationInterval(models.Model):
    day                     = models.ForeignKey(TodayReservation, on_delete = models.CASCADE, default = DEFAULT_ID)
    timeIntervalBegin       = models.IntegerField()
    timeIntervalEnd         = models.IntegerField()
    seatsLeft               = models.IntegerField()

class Seat(models.Model):
    timeInterval        = models.ForeignKey(ReservationInterval, on_delete = models.CASCADE, default = DEFAULT_ID)
    

restraunts/forms.py
from django import forms

from .models import Restraunt

class RestrauntModelForm(forms.ModelForm):
    class Meta:
        model = Restraunt
        fields = [
            'name',
            'city',
            'address',
            'state',
            'seatsAvailable',
            'cuisine',
            'beginTime',
            'endTime',
            'priceRange'
            
        ]
    #def clean_name(self):
    #    self = self.cleaned_data.get('name')
    #    if name.lower() == 'abc':
    #        raise forms.ValidationError("This is not a valid name")
    #    return name

restraunts/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, redirect
from django.views import View
from .forms import RestrauntModelForm
from .models import Restraunt, ReservationDate, TodayReservation, ReservationInterval, Seat
from reservations.views import ReservationModelForm
from reservations.models import Reservation
from django.utils import timezone
from django.db.models import Q
# BASE VIEW Class = VIEW
from django.views.generic import DetailView



def searchRest(request):
    template = 'restraunts/restraunts_list.html'
    query = request.GET.get('q') #take the item searched from the url(comes from form that user fills) so we can see if it exists in the db

    if query:
        results = Restraunt.objects.filter(Q(name__icontains=query) 
                                        | Q(cuisine__icontains=query)
                                        | Q(city__icontains=query)
                                        
                                                                    ) # icontains - returns whatever we are querying in the db
    else:
        results = Restraunt.objects.all()
    if results:
        context = {
        'results' : results
    }

    else:
        #if there are no results that meet the criteria we want to display all the restraunts
        results = Restraunt.objects.all()
        context = {
        'results' : results
    }

    return render(request,template,context)

class RestrauntReservationsView(DetailView):
    template_name = 'restraunts/restraunt_reservations.html'
   # queryset = Reservation.objects.all()    #reservations/<modelname>_list.html is the template needed

    def get(self, request, id=None, *args, **kwargs):
        id_ = self.kwargs.get("id")

        rest = Restraunt.objects.get(id = id_)
        dates = list(ReservationDate.objects.filter(restraunt = rest))
        allTimes = []
        dates_and_times = {}

        for d in dates:
            try:
                day_of_res = TodayReservation.objects.get(reservationDate = d)
            except TodayReservation.DoesNotExist:
                day_of_res = None
            
            try:
                times = list(ReservationInterval.objects.filter(day = day_of_res))
            except ReservationInterval.DoesNotExist:
                times = None

            dates_and_times[day_of_res] = times

            allTimes = allTimes + times 

        for x, y in dates_and_times.items():
            print(x, y)
        print(dates_and_times)

        context = {
            "dates" : dates,
            "allTimes" : allTimes,
            "dates_and_times": dates_and_times
            
        }
        
        return render(request, self.template_name, context)      

class RestrauntCreateView(View):
    #Staff can create a new restraunt(Unlikely going to be used much since there is one restraunt owner)
    template_name = "restraunts/restraunt_create.html"

    def get(self, request, id=None, *args, **kwargs):
        form = RestrauntModelForm()

        context = {"form": form}
        return render(request, self.template_name, context)

    def post(self, request, id=None, *args, **kwargs):
        #when user submits form it goes to a post request and this function catches is it and saves in the db
        form = RestrauntModelForm(request.POST)

        if form.is_valid():
            form.save()
            form = RestrauntModelForm()
        context = {"form": form}
        return render(request, self.template_name, context)


class RestrauntUpdateView(View):
    #Staff can update the restraunt information
    template_name = "restraunts/restraunt_update.html"

    def get_object(self):
        id = self.kwargs.get('id')
        obj = None
        if id is not None:
            obj = get_object_or_404(Restraunt, id=id)

        return obj

    def get(self, request, id=None, *args, **kwargs):
        context = {}
        obj = self.get_object()
        if obj is not None:
            form = RestrauntModelForm(instance=obj)
            context['object'] = obj
            context['form'] = form

        return render(request, self.template_name, context)

    def post(self, request, id=None, *args, **kwargs):
        context = {}
        obj = self.get_object()
        if obj is not None:
            form = RestrauntModelForm(request.POST, instance=obj)
            if form.is_valid():
                form.save()
            context['object'] = obj
            context['form'] = form
        return render(request, self.template_name, context)


class RestrauntListView(View):
    template_name = "restraunts/restraunts_list.html"
    queryset = Restraunt.objects.all()

    def get_queryset(self):
        return self.queryset

    def get(self, request, *args, **kwargs):
        context = {'object_list': self.queryset}
        return render(request, self.template_name, context)

class RestrauntView(View):
    template_name = "restraunts/restraunt_detail.html"

    def get(self, request, id=None, *args, **kwargs):
        context = {}
        
        if id is not None:
            obj = get_object_or_404(Restraunt, id=id)

            context['object'] = obj
            context['rname'] = obj.name
           
        return render(request, self.template_name, context)

    def post(self, request, id=None, *args, **kwargs):
        obj = get_object_or_404(Restraunt, id=id)
        
        res = Restraunt.objects.get(pk = id)
        when_reserved = request.POST.get('when_reserved')
 
        path = str(id) + "/reserve?reserved=" + str(when_reserved) 
       
        return HttpResponseRedirect(path, when_reserved)

def replaceQuater(time):
    #replaces last 2 digits if they are 60 to 00, because hour is only 60 min 
    if(int(time[2]+time[3]) > 45):
            temp = int(time[1]) + 1
            time = time[:1] + str(temp) + '00'
    return time

def addDigit(time):
    #adds 0 to begining to conver 8am to military 0800
    if(len(time) == 3):
        time = '0' + time
    return time

def replaceHour(time):
    #makes sure that 19 45 switched to 20 00 
    if(int(time) == 11000):
        time = 2000
        print(time)
    return int(time)

def toTime(num):
    #Calls all the functions to turn a number into proper time( because when adding time intervals 14:45 + 15 = 14:60 and it should be 15:00, etc.)
    num = str(num)
    num = addDigit(num)
    num = replaceQuater(num)
    num = replaceHour(num)
    return num

def populateDay(begInt,endInt, endInterval,day_of_res, rest):
        #populates the day in db with 2 hour intervals
        #assumption is that time to eat takes 2 hours
    try:   
        interval = ReservationInterval.objects.get(day = day_of_res, timeIntervalBegin = begInt)
          
    except ReservationInterval.DoesNotExist:
        i = 0
        while(endInt < endInterval -15):
            begInt = toTime(begInt)
            endInt = toTime(endInt)

            res_time_intervals = ReservationInterval(day = day_of_res, timeIntervalBegin = begInt, timeIntervalEnd = endInt, seatsLeft = rest.seatsAvailable)
            res_time_intervals.save()
      
            begInt += 15
            endInt  +=  15
            i+=1

def updateSeats(b,e,endInterval,obj,date):
    print("res " + str(date))
    #Goes thru time intervals and if there are seats available in those intervals(2 hour window)
    #if there are seats available we decrement them by one
    #if not we want to tell the user he cannot reserve

    for i in range(8):      
        b = toTime(b)
        e = toTime(e)
                
        if(e < endInterval):
            try:
                interval = ReservationInterval.objects.get(day = date,timeIntervalBegin = b)
              
            except ReservationInterval.DoesNotExist:
                interval = None

            if  interval:
                sLeft = interval.seatsLeft -1
                if(sLeft > 0):
                    interval.seatsLeft = sLeft
                    interval.save()                
                else:
                    #TODO Don't let user make reservation if there are no seats
                    print("NO SEATS")
       
            b = b + 15
            e = e + 15
            b = toTime(b)
            e = toTime(e)
    

class RestrauntReservationCreateView(View):
    # Creates a restraunt and puts it in the database
    template_name = "restraunts/restraunt_reserve.html"
    
    def updateRestrauntDB(attr,id):
        obj = Restraunt.objects.get(pk=id)

    def get(self, request, id):
        obj = Restraunt.objects.get(pk=id)
        resDate = request.GET.get('reserved', ' ')
    
        obj = Restraunt.objects.get(pk=id)
        request.session['resDate'] = resDate
        
        print(resDate)

        d = ReservationDate(restraunt = obj, date = resDate)
        res_day = TodayReservation(reservationDate = d)

        dateExists = ReservationDate.objects.filter(date = resDate).count()
        if dateExists < 1:
            d.save()

        form = ReservationModelForm()
        context = {"form": form, "restraunt_id": id,
                   "restraunt_name": obj.name}

        return render(request, self.template_name, context)

    def post(self, request, id, *args, **kwargs):
        red = request.META['HTTP_REFERER'] #redirects to the same page
        form = ReservationModelForm(request.POST)
        
        if form.is_valid():
            dt = request.session.get('resDate')
            obj = Restraunt.objects.get(pk=id)
            #Gets the date from the get method above so we can 
           
            instance = form.save(commit=False) #dont let the form save
            instance.restraunt_reserved = obj.name

restraunts/templates/restraunts/restraunt_create.html
{% extends 'base.html' %}

{% block content %}

    <form action = '.' method = 'POST'>{% csrf_token %}
        {{ form.as_p }}
        <button class = "button">Save</button>
    </form>


{% endblock %}

restraunts/templates/restraunts/restraunt_delete.html
{% extends 'base.html' %} 

{% block content %}

  <h1>Delete: {{ object.name }}</h1>

  <form action="." method="POST"> {%csrf_token %}

    <h1>Do you want to delete the restaurant " {{ object.name }}"?</h1>
    <button class="button">Yes</button>
  </form>

{% endblock %}

<!--If it is a single owner for all the restraunts, should we even be able to add restraunts and delete them, given that it is not going to change drastically maybe we should add it as an admin and make updates on asking-->

restraunts/templates/restraunts/restraunt_detail.html
{% extends 'base.html' %}

{% block content %}

  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

  <script>
      $( function() {
        var date = $('#datepicker').datepicker({ dateFormat: 'yy-mm-d' }).val();
        $( "#datepicker" ).datepicker();
      } );
  </script>

{% if request.user.is_staff %}
 <a href ="{{object.id}}/reservations" style = "margin-left:20px;"> Check seats available</a>
{% endif %}


  <p style="margin-left: 20px;">Name : {{ object.name }}</p>
  <p style="margin-left: 20px;">Address : {{ object.address }}</p>
  <p style="margin-left: 20px;">City : {{ object.city }}</p>
  <p style="margin-left: 20px;">State : {{ object.state }}</p>
  <p style="margin-left: 20px;">Cuisine : {{ object.cuisine }}</p>
  <p style="margin-left: 20px;">Price range : {{ object.priceRange }}</p>
  <p style= "margin-left: 20px;">Start Time : {{ object.beginTime}}</p>
  <p style= "margin-left: 20px;">End Time : {{ object.endTime }}</p>

      <!-- We don't want to print out how many seats are available
                                                      because if there a lot of empty seats the customer might not reserve-->
      
  <form action = {{object.id}} method = "POST">{% csrf_token %}
    <p style="font-size:130%; margin-left: 20px;">Date: <input type="text" style = "width: 100px;  " id ="datepicker" name = "when_reserved"  autocomplete="off"></p>
    <button class = "btn btn-success" style=" background-color:red; border-color:black ; margin-left: 20px;" > Continue </button>
  </form>
    <br>
    <h1 style ="margin-left: 20px;" >Few seats left available. Reserve now!</h1>

{% endblock %}

restraunts/templates/restraunts/restraunt_reservations.html
{% for obj in dates %}

<a href = "#{{ obj.date }}" style="margin-left: 20px;">{{ obj.date }}</a>

{% endfor %}
<br>

{% for key,values in dates_and_times.items %}


<p  id ="{{ key.reservationDate.date }}" style="margin-left: 20px;"></p>
<br>
<br>

<tr>
 
  <td>{{key.reservationDate.date }}</td> <br>
  {% for v in values %}
  
  <br>
  
  <a >{{ v.timeIntervalBegin }} - {{ v.seatsLeft }}</a>
  <br>


  {% endfor %}
 
</tr>

<br>
<br>
<br>

{% endfor %}

restraunts/templates/restraunts/restraunt_reserve.html
{% extends 'base.html' %} 

{% block content %}

  <h1>Making a reservation for {{ restraunt_name }}</h1>
  <br>

  <form action="." method="POST">{% csrf_token %} 
    {{ form.as_p }}

    <button class = "btn btn-success" style=" background-color:red; border-color:black ; " >Save</button>
  </form>
  {{ when_reserved }}

  {{pr}}

{% endblock %}

restraunts/templates/restraunts/restraunt_update.html
{% extends 'base.html' %}

    {% block content %}

    <h1>Update: {{ object.name }} </h1>

    <form action = '.' method = 'post'>{%csrf_token %}
        {{ form.as_p }}
        <input type = 'submit' value = 'Save' />
    </form>

{% endblock %}

restraunts/templates/restraunts/restraunts_list.html
{% extends 'base.html' %} 
{% block content %}
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">


  <form method="GET" action="{% url 'restraunts:searchRest' %}">
    <input name="q" value="{{request.GET.q}}" placeholder="Search.." style="margin-left: 20px;" />
    <button
      class="btn btn-success"
      type="submit"
      style=" background-color:red; border-color:black"
    >
      Search
    </button> 

    {% if request.user.is_staff %}
      <a href ="create/" style = "margin-left:20px;"> Add a new restaurant</a>
    {% endif %}

  </form>

  {% for obj in results %} 

  <div class="w3-container">
    </br>
      <div class="w3-card-4" style="width:30%;  box-shadow: 0 4px 8px 0 rgba(255, 111, 222, 11.2), 0 6px 20px 0 rgba(255, 0, 0, 11.2);">
        <header class="w3-container" style = "background:red; color:white">
          <h1 align="center"><a href="../{{obj.id}}">{{obj.name}}</a></h1>
        </header>

        <div class="w3-container">
          <br>
          <p>City : {{ obj.city }}</p>
          <p>State : {{ obj.state }}</p>
          <p>Cuisine : {{ obj.cuisine }}</p>
          <p>Price range: {{ obj.priceRange }}</p>
        </div>

      </div>
    </div>
    </br>
  {% endfor %}

  {% for instance in object_list %} 

    <div class="w3-container">
      </br>

        <div class="w3-card-4" style="width:30%;  box-shadow: 0 4px 8px 0 rgba(255, 111, 222, 11.2), 0 6px 20px 0 rgba(255, 0, 0, 11.2);">
          <header class="w3-container" style = "background:red; color:white">
            <h1 align = "center"><a href="{{instance.id}}">{{instance.name}}</a></h1>
          </header>

          <div class="w3-container">
          <br>
            <p>City : {{ instance.city }}</p>
            <p>State : {{ instance.state }}</p>
            <p>Cuisine : {{ instance.cuisine }}</p>
            <p>Price range: {{ instance.priceRange }}</p>
          </div>

        </div>
      </br>
    </div>
      
  {% endfor %} 
{% endblock %}